name: Build and deploy to App Service

env:
  AZURE_WEBAPP_NAME: nblackout-money-manager
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '9.0.x'

concurrency:
  group: money-manager
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore tools
        run: dotnet tool restore

      - name: Restore packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore --nologo

      - name: Test
        run: dotnet test --no-restore --verbosity minimal

      - name: Mutation testing Write
        run: dotnet stryker -p Write.App -f ../stryker-config.json
        working-directory: Tests/Write.App.Tests

      - name: Mutation testing Read
        run: dotnet stryker -p Read.App -f ../stryker-config.json
        working-directory: Tests/Read.App.Tests

      - name: Mutation testing Client.Write
        run: dotnet stryker -p Client.Write.App -f ../stryker-config.json
        working-directory: Tests/Client.Write.App.Tests

      - name: Mutation testing Client.Read
        run: dotnet stryker -p Client.Read.App -f ../stryker-config.json
        working-directory: Tests/Client.Read.App.Tests

      - name: Publish API
        run: dotnet publish Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/artifacts/api --nologo

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: .artifact-api
          path: ${{env.DOTNET_ROOT}}/artifacts/api

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: .artifact-api

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}